### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by arnaudsj** [apcode/tensorflow_fasttext#2]
Hi,

Thank you for making this code available. I am attempting to run against a simple dataset of mine but I am running into the following error (any pointers):

`Processing training dataset file
Processing test dataset file
data/mydataset.train.vocab
87898
Testing
INFO:tensorflow:Using config: {'_log_step_count_steps': 100, '_master': '', '_evaluation_master': '', '_model_dir': 'data/models/mydataset', '_save_checkpoints_secs': None, '_task_id': 0, '_keep_checkpoint_max': 5, '_task_type': None, '_tf_random_seed': None, '_num_worker_replicas': 0, '_save_checkpoints_steps': 1000, '_session_config': , '_save_summary_steps': 100, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x117c32e80>, '_num_ps_replicas': 0, '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_environment': 'local', '_keep_checkpoint_every_n_hours': 10000}
STARTING TRAIN
ParseSpec {'label': FixedLenFeature(shape=(1,), dtype=tf.int64, default_value=None), 'text': VarLenFeature(dtype=tf.string)}
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into data/models/mydataset/model.ckpt.
INFO:tensorflow:loss = 3.87008, step = 1
2017-08-23 14:27:17.797448: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Received a label value of -1 which is outside the valid range of [0, 47).  Label values: 19 41 22 19 31 1 39 8 22 4 43 12 27 39 19 43 22 44 21 19 4 42 19 21 27 9 41 6 41 44 1 14 5 6 37 6 41 1 6 16 42 39 4 0 25 14 4 30 6 31 9 19 41 41 41 6 23 1 19 19 9 17 26 41 43 19 41 23 22 14 14 9 6 41 1 1 -1 6 23 31 16 14 20 6 41 19 4 1 21 31 23 34 4 6 11 6 1 4 30 32 44 17 43 4 44 32 13 9 44 4 41 41 4 6 9 19 22 40 9 23 4 21 41 0 6 5 20 37
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "~/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of -1 which is outside the valid range of [0, 47).  Label values: 19 41 22 19 31 1 39 8 22 4 43 12 27 39 19 43 22 44 21 19 4 42 19 21 27 9 41 6 41 44 1 14 5 6 37 6 41 1 6 16 42 39 4 0 25 14 4 30 6 31 9 19 41 41 41 6 23 1 19 19 9 17 26 41 43 19 41 23 22 14 14 9 6 41 1 1 -1 6 23 31 16 14 20 6 41 19 4 1 21 31 23 34 4 6 11 6 1 4 30 32 44 17 43 4 44 32 13 9 44 4 41 41 4 6 9 19 22 40 9 23 4 21 41 0 6 5 20 37
	 [[Node: SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](SparseSoftmaxCrossEntropyWithLogits/Reshape, SparseSoftmaxCrossEntropyWithLogits/Reshape_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classifier.py", line 218, in <module>
    tf.app.run()
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "classifier.py", line 208, in main
    FastTrain()
  File "classifier.py", line 181, in FastTrain
    estimator.train(input_fn=train_input, steps=FLAGS.train_steps, hooks=None)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 686, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 518, in run
    run_metadata=run_metadata)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 862, in run
    run_metadata=run_metadata)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 972, in run
    run_metadata=run_metadata)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 818, in run
    return self._sess.run(*args, **kwargs)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Received a label value of -1 which is outside the valid range of [0, 47).  Label values: 19 41 22 19 31 1 39 8 22 4 43 12 27 39 19 43 22 44 21 19 4 42 19 21 27 9 41 6 41 44 1 14 5 6 37 6 41 1 6 16 42 39 4 0 25 14 4 30 6 31 9 19 41 41 41 6 23 1 19 19 9 17 26 41 43 19 41 23 22 14 14 9 6 41 1 1 -1 6 23 31 16 14 20 6 41 19 4 1 21 31 23 34 4 6 11 6 1 4 30 32 44 17 43 4 44 32 13 9 44 4 41 41 4 6 9 19 22 40 9 23 4 21 41 0 6 5 20 37
	 [[Node: SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](SparseSoftmaxCrossEntropyWithLogits/Reshape, SparseSoftmaxCrossEntropyWithLogits/Reshape_1)]]

Caused by op 'SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits', defined at:
  File "classifier.py", line 218, in <module>
    tf.app.run()
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "classifier.py", line 208, in main
    FastTrain()
  File "classifier.py", line 181, in FastTrain
    estimator.train(input_fn=train_input, steps=FLAGS.train_steps, hooks=None)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 241, in train
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 630, in _train_model
    model_fn_lib.ModeKeys.TRAIN)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 615, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "classifier.py", line 121, in model_fn
    labels=labels, logits=logits))
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1706, in sparse_softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2491, in _sparse_softmax_cross_entropy_with_logits
    features=features, labels=labels, name=name)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "~/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Received a label value of -1 which is outside the valid range of [0, 47).  Label values: 19 41 22 19 31 1 39 8 22 4 43 12 27 39 19 43 22 44 21 19 4 42 19 21 27 9 41 6 41 44 1 14 5 6 37 6 41 1 6 16 42 39 4 0 25 14 4 30 6 31 9 19 41 41 41 6 23 1 19 19 9 17 26 41 43 19 41 23 22 14 14 9 6 41 1 1 -1 6 23 31 16 14 20 6 41 19 4 1 21 31 23 34 4 6 11 6 1 4 30 32 44 17 43 4 44 32 13 9 44 4 41 41 4 6 9 19 22 40 9 23 4 21 41 0 6 5 20 37
	 [[Node: SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"](SparseSoftmaxCrossEntropyWithLogits/Reshape, SparseSoftmaxCrossEntropyWithLogits/Reshape_1)]]
`

The same mydataset.train / mydataset.test is processed fine by fasttext (C++ version). Thank yoiiu in advance!

**Comment by apcode** [comment]
Hi, so it looks like you have a label of -1, which will cause this exception as the label is the model output class so it must be in the range [0:num_classes).

Did you use process_input? and did you use text_input or facebook_input?
If you look in process_input.py in both ParseFacebookInput and ParseTextInput I subtract 1 from the label read. This was how the facebook input format works E.g. https://github.com/apcode/tensorflow_fasttext/blob/7610d322bfd5b43ae0ec4ee63c2111f66d344f0a/process_input.py#L74

I suspect for text input this might be incorrect. For example if your label file already has labels in the range 0:num_classes this would cause this error.

You could try editing ParseTextInput to not subtract 1 from the label. 

I should probably change that anyway.

**Comment by apcode** [comment]
I tried updating this for text format inputs to use 0-offset labels rather than 1-offset.

commit: 0c86610c9522d937dcc68cce54d30d6724aa5f4d

**Comment by apcode** [comment]
Sebastien, 
Did this work for you? If so I can close this issue.

**Comment by arnaudsj** [comment]
Hi @apcode, I tried and it failed again, but after I read you changes, I saw you forgot to make the change to facebook-input as well so I did this and it finally worked:
```
diff --git a/process_input.py b/process_input.py
index 1bb443c..d5dd04d 100644
--- a/process_input.py
+++ b/process_input.py
@@ -62,7 +62,7 @@ def ParseFacebookInput(inputfile, ngrams):
         words = words[2:]
         examples.append({
             "text": words,
-            "label": label - 1
+            "label": label
         })
         if ngrams:
             examples[-1]["ngrams"] = NGrams(words, ngrams)
```

Thank you for your help! I have more questions, but I will open other issues for sake of clarity.

**Comment by apcode** [comment]
Ah, for some reason I took facebook_input as being 1-offset. 
I'll add your fix in.
Thanks.
